# Generated by Django 4.2.2 on 2023-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spofify_id',
            field=models.CharField(default='defaultValue'),
        ),
    ]
