# Generated by Django 4.2.2 on 2023-08-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_artist_spofify_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='spofify_id',
            new_name='spotify_id',
        ),
    ]
